sudo: false

language: node_js

node_js:
  - "4"
  - "5"
  - "6"

cache:
  directories:
    - node_modules

install:
  - export CXX="g++-4.8"
  - npm install

script:
  - npm run test
  - npm run build
