sudo: false

language: node_js

node_js:
  - "v0.10.46"
  - "4"
  - "6"

cache:
  directories:
    - node_modules

before_install: npm install -g grunt-cli

install: npm install

script: npm run test
